# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - 'v*'
    branches: [ "main" ]


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        cache: true

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish Onion.Demo.WebApi/Onion.Demo.WebApi.csproj -c Release -o ./publish

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: OnionApp
        path: ./publish

    # - name: Create GitHub Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     tag_name: ${{ github.ref_name }}   # 自动用 tag 名作为 Release 名
    #     name: Release ${{ github.ref_name }}
    #     files: ./publish/**                # 把编译产物上传为 release 附件
